# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://muted.se
title: Muted
email: hostmaster@muted.se
author: Joakim Dellrud
description: >
  Muted assist in consulting privacy awarness and services to individuals or 
  companies.
copyright: ''
credits: ''
# [header source](https://search.creativecommons.org/photos/b52666e9-f01c-4f95-bae3-638264722029) & [footer source](https://search.creativecommons.org/photos/1a1415cc-27b6-4c41-91fa-0dd87be7c365)
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Blog
    url: https://b-landia.net
  - title: Github
    url: https://github.com/spixx
